# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    """
        Interface gráfica para a janela de diálogo de seleção de tipo de usuário.

        Attributes
        ----------
        buttonBox : QtWidgets.QDialogButtonBox
            Caixa de botões que inclui botões "Cancelar" e "Ok".
        checkBox : QtWidgets.QCheckBox
            Checkbox para seleção do tipo "Administrador".
        checkBox_2 : QtWidgets.QCheckBox
            Checkbox para seleção do tipo "Funcionário".
        checkBox_3 : QtWidgets.QCheckBox
            Checkbox para seleção do tipo "Entregador".
        checkBox_4 : QtWidgets.QCheckBox
            Checkbox para seleção do tipo "Fornecedor".

        Methods
        -------
        setupUi(self, Dialog)
            Configura a interface gráfica da janela de diálogo.
        retranslateUi(self, Dialog)
            Define os textos dos elementos da interface gráfica.
    
    """
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 242)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(90, 30, 111, 20))
        self.checkBox.setAutoExclusive(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 60, 101, 20))
        self.checkBox_2.setAutoExclusive(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 90, 91, 20))
        self.checkBox_3.setAutoExclusive(True)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(90, 120, 91, 20))
        self.checkBox_4.setAutoExclusive(True)
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName("checkBox_4")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        """
            Define os textos dos elementos da interface gráfica.

            Parameters
            ----------
            Dialog : QtWidgets.QDialog
            Instância da janela de diálogo.
        
        """
        
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Administrador"))
        self.checkBox_2.setText(_translate("Dialog", "Funcionario"))
        self.checkBox_3.setText(_translate("Dialog", "Entregador"))
        self.checkBox_4.setText(_translate("Dialog", "Fornecedor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
