# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_busca.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Buscar(object):
    """
        Classe responsável por configurar a interface gráfica da janela de busca.

        Attributes
        ----------
        centralwidget : QtWidgets.QWidget
            Widget central que contém todos os elementos da interface.
        label : QtWidgets.QLabel
            Rótulo associado ao campo de entrada do CPF.
        pushButton : QtWidgets.QPushButton
            Botão para realizar a busca.
        label_2 : QtWidgets.QLabel
            Rótulo associado ao campo de entrada do nome.
        label_3 : QtWidgets.QLabel
            Rótulo associado ao campo de entrada do endereço.
        label_4 : QtWidgets.QLabel
            Rótulo associado ao campo de entrada da data de nascimento.
        label_5 : QtWidgets.QLabel
            Rótulo principal da tela de busca.
        pushButton_2 : QtWidgets.QPushButton
            Botão para voltar.
        lineEdit : QtWidgets.QLineEdit
            Campo de entrada para o CPF.
        lineEdit_2 : QtWidgets.QLineEdit
            Campo de entrada para o nome.
        lineEdit_3 : QtWidgets.QLineEdit
            Campo de entrada para o endereço.
        lineEdit_4 : QtWidgets.QLineEdit
            Campo de entrada para a data de nascimento.

        Methods
        -------
        setupUi(MainWindow: QtWidgets.QMainWindow)
            Configura a interface gráfica da janela de busca.
        retranslateUi(MainWindow: QtWidgets.QMainWindow)
            Traduz os elementos da interface para o idioma desejado.

    """
    
    def setupUi(self, MainWindow):
       def setupUi(self, MainWindow):
        """
            Configura a interface gráfica da janela de busca.

            Parameters
            ----------
            MainWindow : QtWidgets.QMainWindow
                Referência à janela principal.

        """ 
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 130, 47, 13))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 120, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 210, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 250, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 280, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 470, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 130, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 210, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 250, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 280, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
            Traduz os textos dos elementos da interface gráfica.

            Parameters
            ----------
            MainWindow : QtWidgets.QMainWindow
            Referência à janela principal.

        """
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buscar"))
        self.label.setText(_translate("MainWindow", "Cpf"))
        self.pushButton.setText(_translate("MainWindow", "Buscar"))
        self.label_2.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "Endereço"))
        self.label_4.setText(_translate("MainWindow", "Data de Nasc"))
        self.label_5.setText(_translate("MainWindow", "Tela de Busca"))
        self.pushButton_2.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Buscar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
