# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Inicial(object):

    """
    Classe responsável por configurar e gerenciar a interface gráfica da tela inicial.

    Attributes:
    ----------
        centralwidget (QtWidgets.QWidget): Widget central que contém todos os elementos da interface.
        label_3 (QtWidgets.QLabel): Rótulo exibindo o título da tela.
        pushButton (QtWidgets.QPushButton): Botão 1 na tela inicial.
        pushButton_2 (QtWidgets.QPushButton): Botão 2 na tela inicial.
        pushButton_3 (QtWidgets.QPushButton): Botão 3 na tela inicial.
        menubar (QtWidgets.QMenuBar): Barra de menu da janela principal.
        statusbar (QtWidgets.QStatusBar): Barra de status da janela principal.

    Methods:
    --------
        setupUi(MainWindow):
            Configura a interface gráfica da tela inicial.

        retranslateUi(MainWindow):
            Traduz os textos dos elementos da interface para o idioma configurado.
    """
    
    
    def setupUi(self, MainWindow):
        """
            Configura a interface gráfica da tela inicial.

            Parameters
            ----------
                MainWindow (QtWidgets.QMainWindow): A referência para a janela principal.

        """

        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 60, 200, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 250, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 250, 100, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 500, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
            Traduz os textos da interface para o idioma desejado.

            Parameters
            ----------
            tela_usuario : QtWidgets.QDialog
                A referência para a janela principal.
        """
       
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela Inicial"))
        self.label_3.setText(_translate("MainWindow", "Tela Inicial"))
        self.pushButton.setText(_translate("MainWindow", "Registrar"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.pushButton_3.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Inicial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
